export const WILAYAS = [
    { id: 1, name: "Adrar", nameAr: "أدرار", zone: "South", price: 900, time: "3-5 أيام" },
    { id: 2, name: "Chlef", nameAr: "الشلف", zone: "West", price: 600, time: "2-3 أيام" },
    { id: 3, name: "Laghouat", nameAr: "الأغواط", zone: "South", price: 800, time: "3-4 أيام" },
    { id: 4, name: "Oum El Bouaghi", nameAr: "أم البواقي", zone: "East", price: 600, time: "2-3 أيام" },
    { id: 5, name: "Batna", nameAr: "باتنة", zone: "East", price: 600, time: "2-3 أيام" },
    { id: 6, name: "Béjaïa", nameAr: "بجاية", zone: "Center", price: 500, time: "2-3 أيام" },
    { id: 7, name: "Biskra", nameAr: "بسكرة", zone: "South", price: 800, time: "3-4 أيام" },
    { id: 8, name: "Béchar", nameAr: "بشار", zone: "South", price: 900, time: "3-5 أيام" },
    { id: 9, name: "Blida", nameAr: "البليدة", zone: "Center", price: 400, time: "24 ساعة" },
    { id: 10, name: "Bouira", nameAr: "البويرة", zone: "Center", price: 500, time: "2-3 أيام" },
    { id: 11, name: "Tamanrasset", nameAr: "تمنراست", zone: "South", price: 1200, time: "5-7 أيام" },
    { id: 12, name: "Tébessa", nameAr: "تبسة", zone: "East", price: 700, time: "3-4 أيام" },
    { id: 13, name: "Tlemcen", nameAr: "تلمسان", zone: "West", price: 700, time: "3-4 أيام" },
    { id: 14, name: "Tiaret", nameAr: "تيارت", zone: "West", price: 700, time: "3-4 أيام" },
    { id: 15, name: "Tizi Ouzou", nameAr: "تيزي وزو", zone: "Center", price: 500, time: "2-3 أيام" },
    { id: 16, name: "Algiers", nameAr: "الجزائر", zone: "Center", price: 400, time: "24 ساعة" },
    { id: 17, name: "Djelfa", nameAr: "الجلفة", zone: "South", price: 700, time: "3-4 أيام" },
    { id: 18, name: "Jijel", nameAr: "جيجل", zone: "East", price: 600, time: "2-3 أيام" },
    { id: 19, name: "Sétif", nameAr: "سطيف", zone: "East", price: 500, time: "2-3 أيام" },
    { id: 20, name: "Saïda", nameAr: "سعيدة", zone: "West", price: 700, time: "3-4 أيام" },
    { id: 21, name: "Skikda", nameAr: "سكيكدة", zone: "East", price: 600, time: "2-3 أيام" },
    { id: 22, name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", zone: "West", price: 600, time: "2-3 أيام" },
    { id: 23, name: "Annaba", nameAr: "عنابة", zone: "East", price: 600, time: "2-3 أيام" },
    { id: 24, name: "Guelma", nameAr: "قالمة", zone: "East", price: 600, time: "2-3 أيام" },
    { id: 25, name: "Constantine", nameAr: "قسنطينة", zone: "East", price: 500, time: "2-3 أيام" },
    { id: 26, name: "Médéa", nameAr: "المدية", zone: "Center", price: 500, time: "2-3 أيام" },
    { id: 27, name: "Mostaganem", nameAr: "مستغانم", zone: "West", price: 600, time: "2-3 أيام" },
    { id: 28, name: "M'Sila", nameAr: "المسيلة", zone: "Center", price: 600, time: "3-4 أيام" },
    { id: 29, name: "Mascara", nameAr: "معسكر", zone: "West", price: 600, time: "2-3 أيام" },
    { id: 30, name: "Ouargla", nameAr: "ورقلة", zone: "South", price: 900, time: "3-5 أيام" },
    { id: 31, name: "Oran", nameAr: "وهران", zone: "West", price: 500, time: "2-3 أيام" },
    { id: 32, name: "El Bayadh", nameAr: "البيض", zone: "South", price: 800, time: "3-4 أيام" },
    { id: 33, name: "Illizi", nameAr: "إليزي", zone: "South", price: 1200, time: "5-7 أيام" },
    { id: 34, name: "Bordj Bou Arreridj", nameAr: "برج بوعريريج", zone: "East", price: 500, time: "2-3 أيام" },
    { id: 35, name: "Boumerdès", nameAr: "بومرداس", zone: "Center", price: 400, time: "24 ساعة" },
    { id: 36, name: "El Tarf", nameAr: "الطرف", zone: "East", price: 700, time: "3-4 أيام" },
    { id: 37, name: "Tindouf", nameAr: "تندوف", zone: "South", price: 1200, time: "5-7 أيام" },
    { id: 38, name: "Tissemsilt", nameAr: "تيسمسيلت", zone: "West", price: 700, time: "3-4 أيام" },
    { id: 39, name: "El Oued", nameAr: "الوادي", zone: "South", price: 800, time: "3-4 أيام" },
    { id: 40, name: "Khenchela", nameAr: "خنشلة", zone: "East", price: 700, time: "3-4 أيام" },
    { id: 41, name: "Souk Ahras", nameAr: "سوق أهراس", zone: "East", price: 700, time: "3-4 أيام" },
    { id: 42, name: "Tipaza", nameAr: "تيبازة", zone: "Center", price: 400, time: "24 ساعة" },
    { id: 43, name: "Mila", nameAr: "ميلة", zone: "East", price: 600, time: "2-3 أيام" },
    { id: 44, name: "Aïn Defla", nameAr: "عين الدفلى", zone: "Center", price: 500, time: "2-3 أيام" },
    { id: 45, name: "Naâma", nameAr: "النعامة", zone: "South", price: 800, time: "3-4 أيام" },
    { id: 46, name: "Aïn Témouchent", nameAr: "عين تموشنت", zone: "West", price: 600, time: "2-3 أيام" },
    { id: 47, name: "Ghardaïa", nameAr: "غرداية", zone: "South", price: 900, time: "3-5 أيام" },
    { id: 48, name: "Relizane", nameAr: "غليزان", zone: "West", price: 600, time: "2-3 أيام" },
    { id: 49, name: "El M'Ghair", nameAr: "المغير", zone: "South", price: 800, time: "3-4 أيام" },
    { id: 50, name: "El Meniaa", nameAr: "المنيعة", zone: "South", price: 900, time: "3-5 أيام" },
    { id: 51, name: "Ouled Djellal", nameAr: "أولاد جلال", zone: "South", price: 800, time: "3-4 أيام" },
    { id: 52, name: "Bordj Baji Mokhtar", nameAr: "برج باجي مختار", zone: "South", price: 1500, time: "7-10 أيام" },
    { id: 53, name: "Béni Abbès", nameAr: "بني عباس", zone: "South", price: 1000, time: "5-7 أيام" },
    { id: 54, name: "Timimoun", nameAr: "تيميمون", zone: "South", price: 1000, time: "5-7 أيام" },
    { id: 55, name: "Touggourt", nameAr: "تقرت", zone: "South", price: 800, time: "3-4 أيام" },
    { id: 56, name: "Djanet", nameAr: "جانت", zone: "South", price: 1500, time: "7-10 أيام" },
    { id: 57, name: "In Salah", nameAr: "عين صالح", zone: "South", price: 1200, time: "5-7 أيام" },
    { id: 58, name: "In Guezzam", nameAr: "عين قزام", zone: "South", price: 1500, time: "7-10 أيام" }
];

export const getWilayaById = (id) => WILAYAS.find(w => w.id === Number(id));
export const getWilayaByName = (name) => WILAYAS.find(w => w.nameAr === name || w.name === name);
